// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412183330_AddingSeedingDatabase")]
    partial class AddingSeedingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("DiaryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaryEntryId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaryEntryId");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            DiaryEntryId = 1,
                            Content = "Today I started my new diary app project. I'm excited to see how it turns out!",
                            Created = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "My First Diary Entry"
                        },
                        new
                        {
                            DiaryEntryId = 2,
                            Content = "I had a great day today! I went for a walk in the park and enjoyed the sunshine.",
                            Created = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Sunny Day"
                        },
                        new
                        {
                            DiaryEntryId = 3,
                            Content = "I had a tough day at work today. I'm glad to be home now and relax.",
                            Created = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Tough Day"
                        },
                        new
                        {
                            DiaryEntryId = 4,
                            Content = "I had a wonderful day with my family. We went to the beach and had a picnic.",
                            Created = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Family Day"
                        },
                        new
                        {
                            DiaryEntryId = 5,
                            Content = "I had a wonderful day with my family. We went to the beach and had a picnic.",
                            Created = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Family Day"
                        },
                        new
                        {
                            DiaryEntryId = 6,
                            Content = "I had a productive day today. I finished all my work and even had time to read a book.",
                            Created = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Productive Day"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
